project: &project "Real-Time Accompaniment Generation"
description: "symbolic music generation with XinYue's tokenization and customed RoFormer, trained on pop 909 dataset"

name: &name "old_m2a_aria"
version: &version "1.0"
save_dir: &save_dir "logs/"

loggers:
    - logger1:
      _target_: "pytorch_lightning.loggers.CSVLogger"
    - logger2:
      _target_: "pytorch_lightning.loggers.TensorBoardLogger"
  # wandb_logger:
  #   type: "wandb"
  #   project: *project

datamodule:
  _target_: "src.datamodule.old_pt.datamodule.OldPtDataModule"
  train_config:
    _target_: "src.datamodule.old_pt.datamodule.OldPtDataset"
    batch_size: 2
    num_workers: 0
    file_path: "data/pop909_acc_cp4.pt" # path to the preprocessed training data
    target_length: 384
    tokenization_type: "XinYue's"
    split_ratio: 10
  val_config:
    _target_: "src.datamodule.old_pt.datamodule.OldPtDataset"
    batch_size: 2
    num_workers: 0
    file_path: "data/pop909_acc_cp4.pt"
    target_length: 384
    tokenization_type: "XinYue's"
    split_ratio: 10

model:
  _target_: "src.model.specific_model.old_m2a_roformer.model.OldM2ATransformer"
  local_encoder_network_config: 
    _target_: "src.model.network.customed_roformer_network.CustomedRoformerNetwork"
  global_encoder_network_config:
    _target_: "src.model.network.customed_roformer_network.CustomedRoformerNetwork"
  local_decoder_network_config:
    _target_: "src.model.network.customed_roformer_network.CustomedRoformerNetwork"
trainer:
  max_epochs: 5000
  accelerator: "gpu"
  devices: [0 ]
seed: 42
