project: &project "Real-Time Accompaniment Generation "
description: "symbolic music generation with XinYue's tokenization and customed RoFormer, trained on aria dataset(skyline_v0). The model size is around 0.25 B"

name: &name "old_m2a_aria"
version: &version "1.3"
save_dir: &save_dir "logs/"
loggers:
  csv_logger:
    type: "csv"
  tensorboard_logger:
    type: "tensorboard"
  # - wandb_logger:
  #   type: "wandb"
  #   project: *project_name
  #   entity: "music_generation"
  #   name: "REMI_RoFormer_pop909"
  #   version: "1.0.0"

dataset:
  tokenizer: "XinYue's"
  train_config:
    batch_size: 10
    num_workers: 0
    file_path: "data/data_aria_skyline_v0/aria_skyline_v0_acc_cp10.pt" # path to the preprocessed training data
    target_length: 384
    tokenization_type: "XinYue's"
    split_ratio: 10
  val_config:
    batch_size: 10
    num_workers: 0
    file_path: "data/data_aria_skyline_v0/aria_skyline_v0_acc_cp10.pt"
    target_length: 384
    tokenization_type: "XinYue's"
    split_ratio: 10

model:
  model_name: "XinYue's + customed RoFormer"
  model_type: "Old-M2A-Transformer"
  large: true
  hidden_size: 1152  # Hidden layer dimension of the global model. Overrides 'large' setting if specified.
  num_layers: 12  # Number of Transformer encoder layers in the global model. Overrides 'large' setting if specified.
  num_attention_heads: 12  # Number of attention heads in the global model. Overrides 'large' setting if specified.
  intermediate_size: 4352  # Intermediate size of the feed-forward network in the global model. Overrides 'large' setting if specified.

  # Local Model (Encoder/Decoder) Hyperparameters
  local_model_num_layers: 3  # Number of layers in the local encoder/decoder.
  local_model_num_attention_heads: 8  # Number of attention heads in the local encoder/decoder.
  local_model_intermediate_size: 768  # Intermediate size of the feed-forward network in the local encoder/decoder.
  
trainer:
  max_epochs: 5000
  accelerator: "gpu"
  devices: [ 1, 2 ]
seed: 42
